name: measurand-flask-app
channels:
  - conda-forge
dependencies:
  - marshmallow
  - xmltodict
  - flask
  - requests
  - flask-admin
  - marshmallow-sqlalchemy
  - flask-sqlalchemy
  - python=3.12
  - xmlschema
  - python-graphviz
  - graphviz
  - gunicorn
