name: mdb-test-py3.12
channels:
  - conda-forge
dependencies:
  - marshmallow
  - xmltodict
  - flask
  - requests
  - flask-admin
  - marshmallow-sqlalchemy
  - flask-sqlalchemy
  - python=3.12
  - xmlschema
  - python-graphviz
  - graphviz
  - gunicorn
prefix: /home/rwhite/mambaforge/envs/mdb-test-py3.12
