name: Docker compose action
on: 
  pull_request:
    branchs: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4.2.2

      - name: Create directories
        run: |
          mkdir -p resources/repo/measurand-taxonomy
          mkdir -p resources/repo/m-layer
          mkdir var
      - name: Checkout taxonomy
        uses: actions/checkout@v5
        with: 
          repository: NCSLI-MII/measurand-taxonomy
          path: resources/repo/measurand-taxonomy 

      - name: Checkout mlayer
        uses: actions/checkout@v5
        with: 
          repository: NCSLI-MII/m-layer
          path: resources/repo/m-layer 
      
      - name: Build container
        run: docker compose build

      - name: Start service
        run: docker compose up
