name: validation
on: 
  pull_request:
    branchs: [main]
  workflow_dispatch:

jobs:
  validate-taxonomy:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v5

      - uses: actions/checkout@v5
        with: 
          repository: NCSLI-MII/measurand-taxonomy
          path: resources
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: list resources
        run: |
          ls resources
      - name: DB Init
        id: dbinit
        run: |
          python scripts/dbinit_validate.py -p config/builder_validate.json -m


   

