name: validation-pip
on: 
  pull_request:
    branchs: [main]
  workflow_dispatch:

jobs:
  validate-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Create directories
        run: |
          mkdir -p resources/repo/measurand-taxonomy
          mkdir -p resources/repo/m-layer
      - name: Checkout taxonomy
        uses: actions/checkout@v5
        with: 
          repository: NCSLI-MII/measurand-taxonomy
          path: resources/repo/measurand-taxonomy 

      - name: Checkout mlayer
        uses: actions/checkout@v5
        with: 
          repository: NCSLI-MII/m-layer
          path: resources/repo/m-layer 
      
      - name: Setup python
        uses: actions/setup-python@v6
        with: 
          python-version: '3.10'
          cache: 'pip'

      - name: Pip install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements_pip.txt
            
          #- name: Pip list outdated
          #run: | 
          #pip list --outdated

          #- name: Pip upgrade
          #run: |
          ## pip install $(pip list --outdated | awk '{ print $1 }') --upgrade
          #pip list --format json | jq -r '.[].name' | xargs pip install -U # pypa/pip/issues/4551
          #pip freeze > updated_requirements_pip.txt
      
          #- name: Upload requirements
          #uses: actions/upload-artifact@v4
          #with:
          #name: updated_requirements_pip.txt
          #path: updated_requirements_pip.txt

      - name: list resources
        run: |
          pwd
          echo "Resources"
          ls resources
          echo "Repo"
          ls resources/repo
          echo "Taxonomy"
          ls resources/repo/measurand-taxonomy
          echo "Mlayer"
          ls resources/repo/m-layer
          
      
      - name: Validate taxonomy and mlayer
        id: validate
        run: |
          which python
          python -m unittest tests/test_validate.py 


   

