name: validation
on: 
  pull_request:
    branchs: [main]
  workflow_dispatch:

jobs:
  validate-taxonomy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      
      - name: Checkout taxonomy
        uses: actions/checkout@v5
        with: 
          repository: NCSLI-MII/measurand-taxonomy
          path: resources
      
            #- name: Install build dependencies
            #run: |
            #sudo apt-get update
            #sudo apt-get install -y python3-dev build-essential

            #- name: Install dependencies
            #run: |
            #python -m ensurepip --upgrade
            #python -m pip install --upgrade setuptools
            #pip install -r requirements_pip.txt
            # - name: Setup python
            # uses: actions/setup-python@v6
            # with: 
            # python-version: '3.10'
      
            # - name: Install dependencies
            #run: |
            #pip install --upgrade pip
            # pip install -r requirements_pip.txt

      - name: Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: measurand-flask-app
          environment-file: environment.yml
          miniforge-version: "latest"
          auto-activate-base: true

      - name: Conda environments
        run: |
          conda init
          conda info
          eval "$(mamba shell hook --shell bash)"
          mamba env list
          mamba activate measurand-flask-app
          mamba list
            
      - name: list resources
        run: |
          pwd
          ls
          ls resources
          
      
      - name: DB Init
        id: dbinit
        run: |
          eval "$(mamba shell hook --shell bash)"
          mamba env list
          mamba activate measurand-flask-app
          mamba list
          which python
          python scripts/dbinit_validate.py -p config/builder_validate.json -m


   

