name: validation
on: 
  pull_request:
    branchs: [main]
  workflow_dispatch:

jobs:
  validate-taxonomy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      
      - name: Checkout taxonomy
        uses: actions/checkout@v5
        with: 
          repository: NCSLI-MII/measurand-taxonomy
          path: resources
      
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r requirements_pip.txt
      
      - name: list resources
        run: |
          ls resources
      
      - name: DB Init
        id: dbinit
        run: |
          python scripts/dbinit_validate.py -p config/builder_validate.json -m


   

